import pandas as pd, numpy as np
c=pd.read_csv("chitiet.csv",low_memory=False); g=pd.read_csv("goc.csv",low_memory=False,dtype=str)
c['dct']=pd.to_datetime(c['ngayct_ct'])
g['dg']=pd.to_datetime(g['ngayct'])
j=c.merge(g[['soid','dg','diachi_ban','ma_ncc_hddt','hoadon_ten_tinhtrang','daxoa','sotien_sauvat']],on='soid',how='left')
print("khop ngay ct vs goc:", (j['dct']==j['dg']).mean())
print("chitiet khong join duoc:", j['dg'].isna().sum())
j['m']=j['dg'].dt.to_period('M')
print("\nSo dong chi tiet theo thang (theo ngay hoa don):"); print(j['m'].value_counts().sort_index())
print("\nSo hoa don theo thang:"); print(g['dg'].dt.to_period('M').value_counts().sort_index())
print("\nSo dong/hoa don:", j.groupby('soid').size().describe().round(2).to_dict())
print("\nma_ncc_hddt (ban ra/mua vao) x thang:"); print(pd.crosstab(g['dg'].dt.to_period('M'),g['ma_ncc_hddt']))
print("\ndiachi_ban x thang (hoa don):"); print(pd.crosstab(g['dg'].dt.to_period('M'),g['diachi_ban'].str[:14]))
print("\ntinh trang hoa don:"); print(g['hoadon_ten_tinhtrang'].value_counts(dropna=False))
print("daxoa:", g['daxoa'].value_counts().to_dict())
